# Generated by Django 4.2.7 on 2024-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_answer_question_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/cringy.png', null=True, upload_to='avatars/'),
        ),
    ]
